### ISSUE TITLE
Unable to Add or Delete weekdays or months in Calendar Settings

### ISSUE THREAD

**Issue by King-Wedgie** [DasSauerkraut/calendar-weather#154] opened 2020-10-20 00:08 UTC
Foundry v0.7.4
About Time v0.1.58
Calendar/Weather v3.0.6

Clicking on the add or delete buttons for weekdays and months does nothing; About Time throws an error message in the console (attached and notated).
Saving the calendar causes Foundry to throw an error message.
Era abbreviation is not saved as well; stays as AD even when loading a different default calendar.

All other settings can be changed and saved as normal (weekday and month names, current weekday and month, month length, intercalary, month abbreviation).

[foundry-vtt-console.txt](https://github.com/DasSauerkraut/calendar-weather/files/5405502/foundry-vtt-console.txt)

**Comment by Colliotv** [comment] 2020-10-24 06:57
So look into the code, the breaking change was introduced into this [commit](https://github.com/DasSauerkraut/calendar-weather/commit/14424a9d7a965b67abed029923379ea2126ea443):
when you modified `saveData` to `async saveData`:

as `addMonth` and `addDay` are not awaiting for the result `JSON.parse` is raising an error.
suggested fix would be:

``` JavaScript
this.saveData().then(function(data) {
        this.data = JSON.parse(data);
        let newMonth = new Month("", 30, 30, true);
        this.data.months.push(newMonth);
        this.render(true);
        this.checkBoxes();
}
```

Can do a PR if ya wish :)

**Comment by wepstein712** [comment] 2020-10-25 15:40
I assume since this was commented yesterday it has not been fixed yet?

**Comment by frondeus** [comment] 2020-10-28 09:29
Okay so I tried with `then` approach and it seems to be working but now I cannot modify date or year without any errors.

**Comment by geoidesic** [comment] 2020-10-28 10:40
The problem is that once you make `saveData` and `async` function, then every function that calls `saveData` synchronously will fail – and there are many places where it is called synchronously.

**Comment by geoidesic** [comment] 2020-10-28 10:54
Why does `saveData` stringily the output? It seems like each consumer has to then parse this, why not just return an object?

**Comment by geoidesic** [comment] 2020-10-28 11:12
Added a PR to fix these issues:
https://github.com/DasSauerkraut/calendar-weather/pull/163

**Comment by geoidesic** [comment] 2020-10-28 11:38
I'm not understanding why the async / await change was made to saveData in the first place though. Could you please link to the issue that change solves?

**Comment by geoidesic** [comment] 2020-10-28 12:48
I don't think the async / await change was necessary, nor do I think it solved anything. I think `about-time` is broken, as the `setAbsolute` call is not working.

**Comment by geilt** [comment] 2020-10-29 23:06
If saveData is an Async event it needs to be run THEN the results passed into the JSON.parse function. You can't really push an async result directly into a function call or it will execute before SaveData is done hence the broken json message. 

VM3593:1 Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at HTMLButtonElement.<anonymous> (calendarForm.mjs:194)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)

**Comment by geilt** [comment] 2020-10-29 23:24
I fixed the problem by wrapping the addMonth functions in a .then

Line 192.

html.find(addMonth).click(ev => {
        ev.preventDefault();
        
        this.saveData().then( (result) => {
          this.data = JSON.parse(result);
          let newMonth = new Month("", 30, 30, true);
          this.data.months.push(newMonth);
          this.render(true);
          this.checkBoxes();
        })
      });

**Comment by crichey** [comment] 2020-10-30 16:01
Would love a fix for this....plugin isn't really usable with out it.

**Comment by geoidesic** [comment] 2020-10-31 16:51
@geilt & @crichey & @Colliotv see my PR above fixes the problem being discussed. @geilt not sure why you went to the effort of creating a PR when I already did one.

**Comment by geoidesic** [comment] 2020-10-31 17:54
Updated PR #163 to also fix issues with not being able to save month, day, year.

**Comment by geilt** [comment] 2020-11-01 09:45
Sorry @geoidesic i didn’t see your PR and was just trying to fix it so I could use it and decided to post my change. I also noticed the date month year is horribly broken which I think you just addressed. Not sure if the original Dev is going to maintain this or not, but it’s so useful for immersion. I hope he pulls your patch soon so I can just grab from updater. Thanks.

**Closed** 2020-11-01 20:37 UTC
Labels: bug
